# Generated by Django 4.2 on 2023-04-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_rate_work_project_default_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="default_rate",
            field=models.DecimalField(decimal_places=2, default=90.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="work",
            name="rate",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name="Rate",
        ),
    ]
