# Generated by Django 4.2 on 2023-04-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="delivered_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="paid_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
