# Generated by Django 4.2 on 2023-04-04 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_contact_email"),
        ("projects", "0008_remove_invoice_hours_work_invoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="point_of_contact",
        ),
        migrations.AddField(
            model_name="project",
            name="billing_point_of_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billing",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="business_point_of_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="business",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="technical_point_of_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="technical",
                to="contacts.contact",
            ),
        ),
    ]
