# Generated by Django 4.2 on 2023-04-04 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_company_point_of_contact"),
        ("contacts", "0002_alter_contact_email"),
        ("projects", "0009_remove_project_point_of_contact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="bill_to_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="bill_to_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contacts.contact",
            ),
        ),
    ]
