# Generated by Django 4.2 on 2023-04-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0012_alter_paymentdetails_options_invoice_payment_details_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdetails",
            name="account",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
