# Generated by Django 4.2 on 2023-04-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_paymentdetails_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdetails",
            name="transaction_date",
            field=models.DateTimeField(default="2023-04-04 04:24:31.378820"),
            preserve_default=False,
        ),
    ]
