# Generated by Django 4.2 on 2023-04-04 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_contact_email"),
        ("companies", "0003_alter_company_address_alter_company_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="point_of_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contacts.contact",
            ),
        ),
    ]
